import type { Metadata } from "next";
import "../styles/index.css";
import PublicLayout from "@/components/templates/PublicLayout";
import { exo2Nd } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo2Nd.className}>
        <PublicLayout>{children}</PublicLayout>
      </body>
    </html>
  );
}
